// ─────────────────────────────────────────────────────────────────────────────
// Cut-Katalog — kanonische, strukturierte Cut-Datenbank (Rind + Schwein)
//
// EINE Quelle für: Cut-Atlas (interaktive Tier-Silhouette + Foto-Galerie),
// Cut-Generator (Empfehlungs-Gimmick) und die Bild-Pipeline
// (scripts/cut-images.mjs liest `visualBrief`).
//
// Doktrin (Burggraben 1): alle Texte in EIGENER Formulierung, NIE 1:1 aus
// Fremdquellen. Werte sind redaktionelle Einordnung der Steakakademie.
// ─────────────────────────────────────────────────────────────────────────────

export type Species = 'rind' | 'schwein';

// Garmethoden — Schlüssel für Generator-Matching + Anzeige
export type CookMethod =
  | 'grill-direkt'
  | 'grill-indirekt'
  | 'pfanne'
  | 'smoker'
  | 'sous-vide'
  | 'schmoren'
  | 'ofen';

export const METHOD_LABEL: Record<CookMethod, string> = {
  'grill-direkt': 'Grill (direkt)',
  'grill-indirekt': 'Grill (indirekt)',
  pfanne: 'Pfanne / Cast Iron',
  smoker: 'Smoker / Low & Slow',
  'sous-vide': 'Sous-vide',
  schmoren: 'Schmoren',
  ofen: 'Ofen',
};

// Anlass — Generator-Eingang
export type Occasion = 'date' | 'familie' | 'solo' | 'gaeste' | 'meal-prep';

export const OCCASION_LABEL: Record<Occasion, string> = {
  date: 'Date / zu zweit',
  familie: 'Familien-Grillen',
  solo: 'Solo-Feierabend',
  gaeste: 'Gäste beeindrucken',
  'meal-prep': 'Meal-Prep / viele Esser',
};

// Cut-DNA — fünf Achsen, jeweils 1–5. Basis für das Radar-Diagramm.
export interface CutDna {
  marbling: number; // Marmorierung / intramuskuläres Fett
  tenderness: number; // Zartheit
  fat: number; // Fettanteil gesamt (inkl. Deckel/Rand)
  flavor: number; // Aroma-Intensität
  value: number; // Preis-Leistung (5 = günstig & dankbar, 1 = teuer/Premium)
}

export interface Cut {
  id: string;
  slug: string; // /cuts/<slug> falls eine MDX-Detailseite existiert
  species: Species;
  primal: string; // Teilstück-ID (siehe PRIMALS)
  nameDE: string;
  nameEN: string;
  aka: string[]; // Synonyme / Handelsnamen
  origin: string; // Lage am Tier (Kurztext)
  blurb: string; // 1–2 Sätze Charakteristik
  facts: string; // Kurzfakt (Gewicht/Verwendung)
  dna: CutDna;
  doneness: string; // empfohlene Garstufe
  coreTemp: string; // Kerntemperatur-Empfehlung
  methods: CookMethod[]; // geeignete Garmethoden
  level: number; // Schwierigkeit 1 (Anfänger) – 5 (Profi)
  price: number; // Preisniveau 1 (günstig) – 5 (Premium)
  occasions: Occasion[]; // wofür eignet sich der Cut
  meatTypeMatch: string[]; // Substrings → Mapping auf Rezept-`meatType` (lowercase)
  image: string; // /images/cuts/<slug>.jpg
  visualBrief: string; // EN-Briefing für die FLUX-Bildgenerierung
  hasGuide?: boolean; // true = es gibt eine ausführliche /cuts/<slug>-Seite
  /**
   * true = Bild wurde generativ ERZEUGT oder WESENTLICH VERÄNDERT und wird im
   * Atlas gekennzeichnet (BildCredit/CutImage). Maßstab wie in BildCredit.tsx:
   * reine Farb- und Tonwertkorrektur löst die Kennzeichnung NICHT aus.
   *
   * Der serienweite Ablauf aus `public/images/cuts/CREDITS.md` (Umgebung per
   * nano-banana-pro/edit entfernt, danach einheitliches Studio-Relight) lässt die
   * Anatomie unverändert und gilt deshalb als Bildbearbeitung, nicht als
   * Erzeugung. Gekennzeichnet werden die beiden Fußnoten-Fälle: `porterhouse`
   * (vollständig KI-erzeugt) und `roastbeef`/rumpsteak (Marmorierung ergänzt).
   */
  imageAI?: boolean;
  /** Klartext-Herkunft wie im MDX-Frontmatter; Format siehe BildCredit.tsx. */
  imageSource?: string;
}

export interface Primal {
  id: string;
  species: Species;
  nameDE: string;
  nameEN: string;
  blurb: string;
  // Klickbare Region im Koordinatensystem der Tier-Silhouette (viewBox 0 0 1000 560)
  points: string;
  labelX: number;
  labelY: number;
  fontSize?: number;
  labelColor?: string; // Override für Labels außerhalb des hellen Körpers
  color: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// RIND — Teilstücke (Primals)
// ─────────────────────────────────────────────────────────────────────────────

export const BEEF_PRIMALS: Primal[] = [
  {
    id: 'kopf_backe',
    species: 'rind',
    nameDE: 'Kopf & Backe',
    nameEN: 'Head & Cheek',
    blurb: 'Der dauerhaft arbeitende Kaumuskel (Ochsenbacke) — extrem kollagenreich, geschmort von tiefem Schmelz.',
    points: '226,208 300,214 300,298 252,312 226,298 232,250',
    labelX: 262, labelY: 262, fontSize: 12, color: '#7c3a10',
  },
  {
    id: 'nacken',
    species: 'rind',
    nameDE: 'Nacken',
    nameEN: 'Neck',
    blurb: 'Stark gearbeiteter Muskel — viel Bindegewebe, ideal für Schmorgerichte und Gulasch.',
    points: '300,214 340,214 340,298 300,298',
    labelX: 320, labelY: 258, fontSize: 12, color: '#8a4510',
  },
  {
    id: 'bug',
    species: 'rind',
    nameDE: 'Bug',
    nameEN: 'Chuck',
    blurb: 'Aromatisch und vielseitig: vom günstigen Schmorbraten bis zum überraschend zarten Flat Iron.',
    points: '322,214 405,197 405,289 330,289',
    labelX: 370, labelY: 250, fontSize: 17, color: '#92400e',
  },
  {
    id: 'hochrippe',
    species: 'rind',
    nameDE: 'Hochrippe',
    nameEN: 'Rib',
    blurb: 'Die Königsklasse der Marmorierung — Heimat von Ribeye, Tomahawk und Côte de Bœuf.',
    points: '405,197 498,191 498,289 405,289',
    labelX: 451, labelY: 234, fontSize: 13, color: '#b45309',
  },
  {
    id: 'roastbeef',
    species: 'rind',
    nameDE: 'Roastbeef',
    nameEN: 'Short Loin',
    blurb: 'Das edelste Teilstück: Roastbeef, Filet, T-Bone und Porterhouse stammen alle von hier.',
    points: '498,191 612,189 612,288 498,289',
    labelX: 557, labelY: 228, fontSize: 14, color: '#c2610c',
  },
  {
    id: 'huefte',
    species: 'rind',
    nameDE: 'Hüfte',
    nameEN: 'Sirloin',
    blurb: 'Charaktervoll und vielseitig — von der brasilianischen Picanha bis zum Tri-Tip.',
    points: '612,189 700,190 700,288 612,288',
    labelX: 656, labelY: 228, fontSize: 15, color: '#a16207',
  },
  {
    id: 'keule',
    species: 'rind',
    nameDE: 'Keule',
    nameEN: 'Round',
    blurb: 'Mageres, festes Fleisch vom Hinterbein — die Basis für Tafelspitz, Rouladen und Sauerbraten.',
    points: '700,190 815,210 812,300 766,344 700,351',
    labelX: 760, labelY: 256, fontSize: 17, color: '#78350f',
  },
  {
    id: 'brust',
    species: 'rind',
    nameDE: 'Brust',
    nameEN: 'Brisket',
    blurb: 'Der heilige Gral des American BBQ — 12+ Stunden im Smoker verwandeln Kollagen in Zartheit.',
    points: '330,289 405,289 405,355 350,351',
    labelX: 372, labelY: 328, fontSize: 13, color: '#92400e',
  },
  {
    id: 'duennung',
    species: 'rind',
    nameDE: 'Dünnung',
    nameEN: 'Plate & Flank',
    blurb: 'Die Geheimtipps der Kenner: grobfaserig, maximal aromatisch — Flank, Bavette, Skirt, Onglet.',
    points: '405,289 700,288 700,355 405,355',
    labelX: 548, labelY: 328, fontSize: 14, color: '#a16207',
  },
  {
    id: 'beinscheibe_vorn',
    species: 'rind',
    nameDE: 'Beinscheibe vorn',
    nameEN: 'Front Shank',
    blurb: 'Kollagenreich vom Vorderbein — Basis für kräftige Fonds und Markknochen.',
    points: '350,352 400,352 400,460 366,460 360,400 350,400',
    labelX: 375, labelY: 500, fontSize: 11, labelColor: '#b89066', color: '#5c2c0a',
  },
  {
    id: 'beinscheibe_hinten',
    species: 'rind',
    nameDE: 'Beinscheibe hinten',
    nameEN: 'Hind Shank',
    blurb: 'Das klassische Osso-Buco-Stück vom Hinterbein — lange Schmorzeit, großer Schmelz.',
    points: '696,351 768,347 770,460 736,460 730,400 700,400',
    labelX: 731, labelY: 500, fontSize: 11, labelColor: '#b89066', color: '#5c2c0a',
  },
  {
    id: 'ochsenschwanz',
    species: 'rind',
    nameDE: 'Ochsenschwanz',
    nameEN: 'Oxtail',
    blurb: 'Gelatinereicher Schwanz — ergibt die tiefste, sämigste Schmorsauce überhaupt.',
    points: '812,300 842,320 838,430 818,430 816,340',
    labelX: 830, labelY: 470, fontSize: 11, labelColor: '#b89066', color: '#5c2c0a',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// RIND — Cuts
// ─────────────────────────────────────────────────────────────────────────────

export const BEEF_CUTS: Cut[] = [
  // ── HOCHRIPPE ──────────────────────────────────────────────────────────────
  {
    id: 'ribeye',
    slug: 'ribeye',
    species: 'rind',
    primal: 'hochrippe',
    nameDE: 'Ribeye',
    nameEN: 'Ribeye',
    aka: ['Entrecôte', 'Rib-Eye', 'Hohe Rippe', 'Delmonico'],
    origin: 'Hochrippe, Längsmuskel (longissimus dorsi)',
    blurb: 'Der marmorierteste Klassiker. Das intramuskuläre Fett schmilzt beim Grillen und gibt den unverwechselbaren Buttergeschmack.',
    facts: '300–400 g je Steak · einer der beliebtesten Steakcuts weltweit.',
    dna: { marbling: 5, tenderness: 4, fat: 4, flavor: 5, value: 2 },
    doneness: 'Medium Rare',
    coreTemp: '54–57 °C',
    methods: ['grill-direkt', 'pfanne', 'grill-indirekt'],
    level: 2, price: 4, occasions: ['date', 'gaeste', 'solo'],
    meatTypeMatch: ['ribeye', 'entrecôte', 'entrecote'],
    image: '/images/cuts/ribeye.jpg',
    visualBrief: 'a single thick boneless ribeye steak showing the large round central eye muscle with the crescent-shaped spinalis fat cap on top and rich fine marbling, raw',
    hasGuide: true,
  },
  {
    id: 'tomahawk',
    slug: 'tomahawk',
    species: 'rind',
    primal: 'hochrippe',
    nameDE: 'Tomahawk',
    nameEN: 'Tomahawk Steak',
    aka: ['Cowboy Steak', 'Ribeye am langen Knochen'],
    origin: 'Hochrippe mit komplett freigelegtem (frenched) Rippenknochen',
    blurb: 'Ein Ribeye am langen, blank freigelegten Knochen — der spektakulärste Auftritt am Grilltisch.',
    facts: '800–1200 g · der lange Knochen ist das Erkennungsmerkmal.',
    dna: { marbling: 5, tenderness: 4, fat: 4, flavor: 5, value: 1 },
    doneness: 'Medium Rare (Reverse Sear)',
    coreTemp: '54–56 °C',
    methods: ['grill-indirekt', 'smoker', 'sous-vide'],
    level: 4, price: 5, occasions: ['gaeste', 'date'],
    meatTypeMatch: ['tomahawk'],
    image: '/images/cuts/tomahawk.jpg',
    visualBrief: 'a thick tomahawk steak: a ribeye with the large round central eye muscle and crescent fat cap, attached to a long frenched cleaned rib bone handle, raw',
    hasGuide: false,
  },
  {
    id: 'cote-de-boeuf',
    slug: 'cote-de-boeuf',
    species: 'rind',
    primal: 'hochrippe',
    nameDE: 'Côte de Bœuf',
    nameEN: 'Bone-in Ribeye',
    aka: ['Rib Steak', 'Ribeye am Knochen'],
    origin: 'Hochrippe mit kurzem Rippenknochen',
    blurb: 'Das Ribeye am kurzen Knochen — der Knochen schützt das Fleisch und intensiviert das Aroma.',
    facts: '600–900 g · klassisch für zwei Personen.',
    dna: { marbling: 5, tenderness: 4, fat: 4, flavor: 5, value: 2 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-indirekt', 'pfanne', 'grill-direkt'],
    level: 3, price: 4, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['côte de bœuf', 'cote de boeuf', 'rib steak'],
    image: '/images/cuts/cote-de-boeuf.jpg',
    visualBrief: 'a thick bone-in ribeye (côte de bœuf) steak with the round eye muscle, fat cap, fine marbling and a short rib bone attached, raw',
  },
  {
    id: 'ribeye-cap',
    slug: 'ribeye-cap',
    species: 'rind',
    primal: 'hochrippe',
    nameDE: 'Ribeye Cap',
    nameEN: 'Ribeye Cap',
    aka: ['Spinalis', 'Deckel', 'Rib Cap'],
    origin: 'Sichelförmiger Deckelmuskel (spinalis dorsi) über dem Ribeye',
    blurb: 'Der „Deckel" des Ribeyes — von vielen Köchen als bester Bissen am ganzen Rind gehandelt.',
    facts: 'Oft gerollt und gebunden · extrem marmoriert, selten erhältlich.',
    dna: { marbling: 5, tenderness: 5, fat: 5, flavor: 5, value: 1 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 4, price: 5, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['ribeye cap', 'spinalis'],
    image: '/images/cuts/ribeye-cap.jpg',
    visualBrief: 'a rolled and tied ribeye cap (spinalis) steak, an intensely marbled crescent muscle coiled into a spiral, raw',
  },
  {
    id: 'prime-rib',
    slug: 'prime-rib',
    species: 'rind',
    primal: 'hochrippe',
    nameDE: 'Hochrippenbraten',
    nameEN: 'Prime Rib',
    aka: ['Standing Rib Roast', 'Prime Rib Roast'],
    origin: 'Ganzes Hochrippenstück am Knochen',
    blurb: 'Der ganze Rippenbraten — im Ofen oder Smoker langsam gegart, eine Festtags-Institution.',
    facts: '2–5 kg · klassischer Weihnachts- und Festbraten in den USA.',
    dna: { marbling: 5, tenderness: 4, fat: 4, flavor: 5, value: 2 },
    doneness: 'Medium Rare',
    coreTemp: '54–57 °C',
    methods: ['ofen', 'grill-indirekt', 'smoker'],
    level: 4, price: 4, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['prime rib', 'hochrippenbraten', 'rib roast'],
    image: '/images/cuts/prime-rib.jpg',
    visualBrief: 'a whole standing rib roast (prime rib) with multiple frenched rib bones, a thick marbled meat eye and a golden fat cap, raw',
  },

  // ── ROASTBEEF & FILET ────────────────────────────────────────────────────
  {
    id: 'roastbeef',
    slug: 'rumpsteak',
    species: 'rind',
    primal: 'roastbeef',
    nameDE: 'Roastbeef / Rumpsteak',
    nameEN: 'Striploin',
    aka: ['New York Strip', 'Contre-Filet', 'Sirloin Steak (UK)'],
    origin: 'Roastbeef-Strang (short loin), oberhalb des Filets',
    blurb: 'Fester Biss, ausgewogene Marmorierung und eine charakteristische Fettkante — der Pfannen-Klassiker.',
    facts: '250–350 g je Steak · die Fettkante einritzen, damit sie nicht aufwölbt.',
    dna: { marbling: 3, tenderness: 4, fat: 3, flavor: 4, value: 3 },
    doneness: 'Medium Rare bis Medium',
    coreTemp: '52–55 °C',
    methods: ['pfanne', 'grill-direkt'],
    level: 2, price: 3, occasions: ['solo', 'date', 'familie'],
    meatTypeMatch: ['roastbeef', 'rumpsteak', 'striploin', 'new york'],
    image: '/images/cuts/rumpsteak.jpg',
    visualBrief: 'a thick striploin / roastbeef steak with a firm white fat rim along one edge and a uniform lean muscle, raw',
    // CREDITS.md Fußnote ¹: Marmorierung des mageren Muskels generativ ergänzt
    // (Texturvorlage Unsplash CEsrs0WHOiw). Silhouette, Fettrand und Anschnitt
    // stammen unverändert aus dem Quellfoto.
    imageAI: true,
    imageSource: 'Unsplash · ID CEsrs0WHOiw · sergey-kotenev · Marmorierung generativ ergaenzt (CREDITS.md Fussnote 1)',
  },
  {
    id: 'new-york-strip',
    slug: 'new-york-strip',
    species: 'rind',
    primal: 'roastbeef',
    nameDE: 'New York Strip',
    nameEN: 'New York Strip',
    aka: ['NY Strip', 'Kansas City Strip', 'Strip Steak'],
    origin: 'Roastbeef-Strang (US-Schnitt), entbeint',
    blurb: 'Der US-Klassiker schlechthin: gleichmäßiger, fester Muskel mit kräftigem Rindgeschmack.',
    facts: '280–340 g · in US-Steakhouses der Standard-Cut.',
    dna: { marbling: 4, tenderness: 4, fat: 3, flavor: 4, value: 3 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 2, price: 4, occasions: ['date', 'solo'],
    meatTypeMatch: ['new york strip', 'ny strip', 'strip steak'],
    image: '/images/cuts/new-york-strip.jpg',
    visualBrief: 'a single thick New York strip steak, a uniform fine-grained muscle with a firm fat strip along one edge, raw',
  },
  {
    id: 'club-steak',
    slug: 'club-steak',
    species: 'rind',
    primal: 'roastbeef',
    nameDE: 'Club Steak',
    nameEN: 'Club Steak',
    aka: ['Bone-in Strip', 'Delmonico (regional)'],
    origin: 'Vorderes Roastbeef am kurzen Knochen, ohne Filetanteil',
    blurb: 'Ein Strip am Knochen — wie ein T-Bone, aber ohne den Filet-Anteil. Maximaler Strip-Geschmack.',
    facts: '350–450 g · der Knochen hält das Fleisch saftig.',
    dna: { marbling: 4, tenderness: 4, fat: 3, flavor: 4, value: 3 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 4, occasions: ['date', 'solo'],
    meatTypeMatch: ['club steak'],
    image: '/images/cuts/club-steak.jpg',
    visualBrief: 'a thick bone-in strip steak (club steak), a single striploin muscle attached to an L-shaped bone, no tenderloin portion, raw',
  },
  {
    id: 't-bone',
    slug: 't-bone',
    species: 'rind',
    primal: 'roastbeef',
    nameDE: 'T-Bone',
    nameEN: 'T-Bone Steak',
    aka: ['Bistecca'],
    origin: 'Hinteres Roastbeef am T-Knochen',
    blurb: 'Zwei Cuts in einem: Roastbeef auf der einen, ein kleines Filet auf der anderen Seite des T-Knochens.',
    facts: '500–700 g · der Filetanteil ist kleiner als beim Porterhouse.',
    dna: { marbling: 4, tenderness: 4, fat: 3, flavor: 4, value: 2 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-direkt', 'grill-indirekt', 'pfanne'],
    level: 3, price: 4, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['t-bone', 't bone'],
    image: '/images/cuts/t-bone.jpg',
    visualBrief: 'a single thick T-bone steak with a clearly visible T-shaped bone, a striploin muscle on one side and a small round tenderloin filet on the other, raw',
  },
  {
    id: 'porterhouse',
    slug: 'porterhouse',
    species: 'rind',
    primal: 'roastbeef',
    nameDE: 'Porterhouse',
    nameEN: 'Porterhouse',
    aka: ['Bistecca alla Fiorentina (groß)'],
    origin: 'Hinterstes Roastbeef am T-Knochen, großer Filetanteil',
    blurb: 'Der größere Bruder des T-Bone — mit einem großen, runden Filetstück. Das Steak für zwei.',
    facts: '700–1000 g · der große Filetanteil unterscheidet es vom T-Bone.',
    dna: { marbling: 4, tenderness: 5, fat: 3, flavor: 4, value: 2 },
    doneness: 'Medium Rare',
    coreTemp: '52–56 °C',
    methods: ['grill-indirekt', 'grill-direkt', 'pfanne'],
    level: 4, price: 5, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['porterhouse', 'fiorentina'],
    image: '/images/cuts/porterhouse.jpg',
    visualBrief: 'a single thick porterhouse steak with a clearly visible T-shaped bone, a large striploin muscle on one side and a LARGE round tenderloin filet on the other side, raw',
    // CREDITS.md Fußnote ²: vollständig KI-erzeugtes Eigenbild (Google Gemini),
    // fachlich geprüft und freigegeben. Keine Fremdrechte berührt.
    imageAI: true,
    imageSource: 'Eigenbild · Google Gemini · vollstaendig KI-erzeugt (CREDITS.md Fussnote 2)',
  },
  {
    id: 'filet',
    slug: 'filet',
    species: 'rind',
    primal: 'roastbeef',
    nameDE: 'Filet',
    nameEN: 'Tenderloin',
    aka: ['Filet Mignon', 'Tenderloin', 'Lungenbraten'],
    origin: 'Filetstrang (psoas major), unter der Lende — der zarteste Muskel',
    blurb: 'Der zarteste Muskel des Rinds, fast ohne Eigenfett. Butterzart, dezent im Geschmack.',
    facts: '180–250 g je Steak · extrem zart, wenig Marmorierung.',
    dna: { marbling: 1, tenderness: 5, fat: 1, flavor: 2, value: 1 },
    doneness: 'Rare bis Medium Rare',
    coreTemp: '52–54 °C',
    methods: ['pfanne', 'sous-vide', 'grill-direkt'],
    level: 3, price: 5, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['filet', 'rinderfilet', 'tenderloin', 'mignon'],
    image: '/images/cuts/filet.jpg',
    visualBrief: 'a tall round filet mignon steak, very lean smooth boneless tenderloin, deep ruby red, no fat cap, no marbling, raw',
  },
  {
    id: 'chateaubriand',
    slug: 'chateaubriand',
    species: 'rind',
    primal: 'roastbeef',
    nameDE: 'Chateaubriand',
    nameEN: 'Chateaubriand',
    aka: ['Filet-Mittelstück'],
    origin: 'Dickes Mittelstück des Filetstrangs',
    blurb: 'Das dicke Mittelstück des Filets, klassisch für zwei Personen, oft mit Garn umbunden.',
    facts: '400–600 g · benannt nach dem französischen Schriftsteller.',
    dna: { marbling: 1, tenderness: 5, fat: 1, flavor: 2, value: 1 },
    doneness: 'Medium Rare',
    coreTemp: '54 °C',
    methods: ['pfanne', 'ofen', 'sous-vide'],
    level: 4, price: 5, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['chateaubriand'],
    image: '/images/cuts/chateaubriand.jpg',
    visualBrief: 'a thick cylindrical chateaubriand center-cut tenderloin roast tied with butchers twine at intervals, very lean deep red, raw',
  },

  // ── HÜFTE ────────────────────────────────────────────────────────────────
  {
    id: 'picanha',
    slug: 'picanha',
    species: 'rind',
    primal: 'huefte',
    nameDE: 'Picanha',
    nameEN: 'Picanha',
    aka: ['Tafelspitz-Deckel', 'Rump Cap', 'Coulotte'],
    origin: 'Hüftdeckel mit charakteristischer Fettkappe',
    blurb: 'Das Symbol des brasilianischen Churrasco — mit Fettkappe auf dem Spieß gegrillt. Charaktervoll und saftig.',
    facts: '1–1,5 kg ganzes Stück · Fettkappe immer dranlassen.',
    dna: { marbling: 3, tenderness: 3, fat: 4, flavor: 4, value: 3 },
    doneness: 'Medium Rare bis Medium',
    coreTemp: '52–55 °C',
    methods: ['grill-indirekt', 'grill-direkt', 'smoker'],
    level: 3, price: 3, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['picanha', 'tafelspitz'],
    image: '/images/cuts/picanha.jpg',
    visualBrief: 'a whole triangular picanha (rump cap) with a thick half-moon white fat cap covering one side, deep red meat, raw',
    hasGuide: false,
  },
  {
    id: 'hueftsteak',
    slug: 'hueftsteak',
    species: 'rind',
    primal: 'huefte',
    nameDE: 'Hüftsteak',
    nameEN: 'Top Sirloin',
    aka: ['Sirloin Steak', 'Rumpsteak (regional)'],
    origin: 'Hüfte (Top Sirloin), mager und fest',
    blurb: 'Magerer, fester Cut mit kräftigem Geschmack und sehr gutem Preis-Leistungs-Verhältnis.',
    facts: '200–300 g · gegen die Faser schneiden.',
    dna: { marbling: 2, tenderness: 3, fat: 2, flavor: 4, value: 4 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 2, price: 2, occasions: ['solo', 'familie', 'meal-prep'],
    meatTypeMatch: ['hüftsteak', 'hueftsteak', 'top sirloin', 'sirloin'],
    image: '/images/cuts/hueftsteak.jpg',
    visualBrief: 'a lean top sirloin steak, a firm fine-grained red muscle with a thin fat edge, raw',
  },
  {
    id: 'tri-tip',
    slug: 'tri-tip',
    species: 'rind',
    primal: 'huefte',
    nameDE: 'Tri-Tip',
    nameEN: 'Tri-Tip',
    aka: ['Bürgermeisterstück', 'Pastorenstück', 'Santa Maria Steak'],
    origin: 'Unteres Hüftstück, dreieckige Form',
    blurb: 'Dreieckiger Cut aus Kalifornien — beim Santa-Maria-BBQ über Eichenholz gegrillt. Saftig und aromatisch.',
    facts: '600–900 g · immer gegen die wechselnde Faser schneiden.',
    dna: { marbling: 3, tenderness: 3, fat: 3, flavor: 4, value: 4 },
    doneness: 'Medium Rare',
    coreTemp: '54–57 °C',
    methods: ['grill-indirekt', 'smoker', 'grill-direkt'],
    level: 3, price: 3, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['tri-tip', 'tri tip', 'bürgermeisterstück'],
    image: '/images/cuts/tri-tip.jpg',
    visualBrief: 'a whole triangular tri-tip roast, a boomerang-shaped lean red muscle with a thin fat layer, raw',
    hasGuide: false,
  },

  // ── KEULE ────────────────────────────────────────────────────────────────
  {
    id: 'tafelspitz',
    slug: 'tafelspitz',
    species: 'rind',
    primal: 'keule',
    nameDE: 'Tafelspitz',
    nameEN: 'Tri-Tip Cap / Aitchbone',
    aka: ['Hüftspitze'],
    origin: 'Spitze der Hüfte zur Keule hin',
    blurb: 'Das Herzstück der Wiener Küche — sanft in Bouillon gegart, mit feiner Fettauflage.',
    facts: '1–1,5 kg · klassisch in Rindssuppe gekocht.',
    dna: { marbling: 2, tenderness: 3, fat: 3, flavor: 4, value: 4 },
    doneness: 'Durchgegart (gekocht) / Medium (sous-vide)',
    coreTemp: '56 °C (sous-vide) / 90 °C (gekocht)',
    methods: ['schmoren', 'sous-vide'],
    level: 2, price: 3, occasions: ['familie', 'gaeste'],
    meatTypeMatch: ['tafelspitz'],
    image: '/images/cuts/tafelspitz.jpg',
    visualBrief: 'a whole tafelspitz beef cut, a lean triangular muscle with a thin fat cap on one side, raw',
  },
  {
    id: 'oberschale',
    slug: 'oberschale',
    species: 'rind',
    primal: 'keule',
    nameDE: 'Oberschale',
    nameEN: 'Topside',
    aka: ['Rouladen', 'Top Round'],
    origin: 'Innenseite der Keule, großer magerer Muskel',
    blurb: 'Mager und fest — die klassische Basis für Rouladen, Schnitzel und dünn aufgeschnittenes Roastbeef.',
    facts: 'Bis 4 kg am Stück · in dünne Scheiben für Rouladen.',
    dna: { marbling: 1, tenderness: 2, fat: 1, flavor: 3, value: 5 },
    doneness: 'Schmoren / dünn Medium',
    coreTemp: '56 °C (Roastbeef) / weich geschmort',
    methods: ['schmoren', 'ofen', 'sous-vide'],
    level: 2, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['oberschale', 'rouladen', 'topside'],
    image: '/images/cuts/oberschale.jpg',
    visualBrief: 'a large lean topside beef roast, a big uniform fine-grained red muscle, almost no marbling, raw',
  },
  {
    id: 'unterschale',
    slug: 'unterschale',
    species: 'rind',
    primal: 'keule',
    nameDE: 'Unterschale',
    nameEN: 'Silverside',
    aka: ['Bottom Round', 'Schwanzstück'],
    origin: 'Außenseite der Keule mit Silberhaut',
    blurb: 'Festes, mageres Schmorfleisch — ideal für Sauerbraten und kräftige Braten mit langer Garzeit.',
    facts: 'Bis 5 kg · die namensgebende silbrige Haut entfernen.',
    dna: { marbling: 1, tenderness: 2, fat: 1, flavor: 3, value: 5 },
    doneness: 'Schmoren / Sauerbraten',
    coreTemp: 'weich geschmort',
    methods: ['schmoren', 'ofen'],
    level: 2, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['unterschale', 'sauerbraten', 'silverside'],
    image: '/images/cuts/unterschale.jpg',
    visualBrief: 'a large lean silverside / bottom round beef roast with a silvery membrane on the outside, raw',
  },
  {
    id: 'kugel',
    slug: 'kugel',
    species: 'rind',
    primal: 'keule',
    nameDE: 'Nuss / Kugel',
    nameEN: 'Knuckle',
    aka: ['Runde Nuss', 'Flache Nuss', 'Nussdeckel'],
    origin: 'Vorderer, runder Muskel der Keule',
    blurb: 'Magerer, dankbarer Allrounder — gut für Fondue, Geschnetzeltes oder als mageres Steak.',
    facts: 'Mehrere Teilmuskeln (runde/flache Nuss, Deckel).',
    dna: { marbling: 1, tenderness: 3, fat: 1, flavor: 3, value: 5 },
    doneness: 'Medium / Schmoren',
    coreTemp: '54–56 °C',
    methods: ['pfanne', 'schmoren', 'sous-vide'],
    level: 2, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['nuss', 'kugel', 'knuckle'],
    image: '/images/cuts/kugel.jpg',
    visualBrief: 'a round lean beef knuckle muscle, a smooth ball-shaped fine-grained red cut, raw',
  },
  {
    id: 'schwanzrolle',
    slug: 'schwanzrolle',
    species: 'rind',
    primal: 'keule',
    nameDE: 'Schwanzrolle',
    nameEN: 'Eye of Round',
    aka: ['Semerrolle', 'Eye of Round'],
    origin: 'Hinterer, zylindrischer Muskel der Keule',
    blurb: 'Sehr magerer, gleichmäßiger Zylinder — perfekt für dünn aufgeschnittenes Roastbeef oder Bündnerfleisch.',
    facts: '1,5–2 kg · extrem mager, exakt garen.',
    dna: { marbling: 1, tenderness: 2, fat: 1, flavor: 3, value: 5 },
    doneness: 'Medium Rare (dünn) / Pökeln',
    coreTemp: '54 °C',
    methods: ['ofen', 'sous-vide'],
    level: 3, price: 1, occasions: ['meal-prep', 'familie'],
    meatTypeMatch: ['schwanzrolle', 'eye of round'],
    image: '/images/cuts/schwanzrolle.jpg',
    visualBrief: 'a cylindrical eye of round beef roast, a smooth lean tube-shaped red muscle, almost no fat, raw',
  },

  // ── BUG & SCHULTER ─────────────────────────────────────────────────────────
  {
    id: 'flat-iron',
    slug: 'flat-iron',
    species: 'rind',
    primal: 'bug',
    nameDE: 'Flat Iron',
    nameEN: 'Flat Iron Steak',
    aka: ['Schaufeldeckel', 'Top Blade'],
    origin: 'Schulterblatt-Außenmuskel (ohne zentrale Sehne)',
    blurb: 'Der überraschend zarte Geheimtipp aus der Schulter — nach dem Filet der zweitzarteste Muskel, zum kleinen Preis.',
    facts: '200–300 g · die mittlere Sehne wird herausgeschnitten.',
    dna: { marbling: 4, tenderness: 4, fat: 3, flavor: 4, value: 5 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 2, price: 2, occasions: ['solo', 'date', 'familie'],
    meatTypeMatch: ['flat iron'],
    image: '/images/cuts/flat-iron.jpg',
    visualBrief: 'a flat iron steak, a flat rectangular well-marbled shoulder muscle, raw',
    hasGuide: false,
  },
  {
    id: 'schaufelstueck',
    slug: 'schaufelstueck',
    species: 'rind',
    primal: 'bug',
    nameDE: 'Schaufelstück',
    nameEN: 'Oyster Blade',
    aka: ['Schulterscherzel', 'Dicke Schulter'],
    origin: 'Schulterblatt, dicker Muskelstrang',
    blurb: 'Saftiges Schulterstück mit feiner Fettader — als Steak grillbar, als Braten schmorbar.',
    facts: '1,5–2 kg · vielseitig zwischen Steak und Schmorbraten.',
    dna: { marbling: 3, tenderness: 3, fat: 3, flavor: 4, value: 5 },
    doneness: 'Medium / Schmoren',
    coreTemp: '54–56 °C oder weich geschmort',
    methods: ['schmoren', 'grill-indirekt', 'sous-vide'],
    level: 2, price: 2, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['schaufelstück', 'schaufelstueck', 'oyster blade'],
    image: '/images/cuts/schaufelstueck.jpg',
    visualBrief: 'a beef oyster blade / shoulder roast, a thick muscle with a line of connective tissue running through, raw',
  },
  {
    id: 'chuck-eye',
    slug: 'chuck-eye',
    species: 'rind',
    primal: 'bug',
    nameDE: 'Chuck Eye Steak',
    nameEN: 'Chuck Eye Steak',
    aka: ['Falsches Ribeye', "Poor Man's Ribeye"],
    origin: 'Vordere Fortsetzung des Ribeye-Muskels in der Schulter',
    blurb: 'Das „falsche Ribeye" — direkte Fortsetzung des Ribeye-Muskels, fast so marmoriert, deutlich günstiger.',
    facts: '250–350 g · nur wenige Steaks pro Tier.',
    dna: { marbling: 4, tenderness: 3, fat: 4, flavor: 4, value: 5 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 2, price: 2, occasions: ['solo', 'familie'],
    meatTypeMatch: ['chuck eye'],
    image: '/images/cuts/chuck-eye.jpg',
    visualBrief: 'a chuck eye steak, a well-marbled round shoulder muscle resembling a ribeye, raw',
  },
  {
    id: 'falsches-filet',
    slug: 'falsches-filet',
    species: 'rind',
    primal: 'bug',
    nameDE: 'Falsches Filet',
    nameEN: 'Mock Tender',
    aka: ['Schulterfilet', 'Petite Tender'],
    origin: 'Schulter, filetförmiger Muskel mit Mittelsehne',
    blurb: 'Filetförmig, aber kräftiger im Geschmack — ideal für Schmorgerichte und Gulasch.',
    facts: '800 g–1,2 kg · die Mittelsehne braucht Garzeit.',
    dna: { marbling: 2, tenderness: 2, fat: 2, flavor: 4, value: 5 },
    doneness: 'Schmoren',
    coreTemp: 'weich geschmort',
    methods: ['schmoren', 'sous-vide'],
    level: 2, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['falsches filet', 'mock tender'],
    image: '/images/cuts/falsches-filet.jpg',
    visualBrief: 'a mock tender beef cut, a cone-shaped lean shoulder muscle resembling a tenderloin with a central sinew, raw',
  },
  {
    id: 'nacken',
    slug: 'nacken',
    species: 'rind',
    primal: 'nacken',
    nameDE: 'Nacken / Hals',
    nameEN: 'Chuck Roast',
    aka: ['Nackenbraten', 'Kamm'],
    origin: 'Hals- und Nackenbereich, stark durchwachsen',
    blurb: 'Stark durchwachsenes Schmorfleisch — wird bei langer, sanfter Garung butterzart und saftig.',
    facts: 'Bis 3 kg · Basis für Gulasch und Schmorbraten.',
    dna: { marbling: 3, tenderness: 1, fat: 4, flavor: 5, value: 5 },
    doneness: 'Schmoren / Low & Slow',
    coreTemp: '88–94 °C (weich)',
    methods: ['schmoren', 'smoker'],
    level: 2, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['nacken', 'chuck roast', 'nackenbraten'],
    image: '/images/cuts/nacken.jpg',
    visualBrief: 'a heavily marbled beef chuck / neck roast with thick seams of fat and connective tissue, raw',
  },
  {
    id: 'rindergulasch',
    slug: 'rindergulasch',
    species: 'rind',
    primal: 'bug',
    nameDE: 'Gulasch',
    nameEN: 'Stew Meat',
    aka: ['Würfelfleisch', 'Schmorwürfel'],
    origin: 'Würfel aus Wade, Bug oder Hals',
    blurb: 'Gewürfeltes Schmorfleisch aus den arbeitenden Muskeln — Kollagen macht es nach Stunden samtig.',
    facts: '3–4 cm Würfel · scharf anbraten, dann lange schmoren.',
    dna: { marbling: 3, tenderness: 2, fat: 3, flavor: 5, value: 5 },
    doneness: 'Schmoren',
    coreTemp: 'weich geschmort',
    methods: ['schmoren'],
    level: 1, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['gulasch', 'stew'],
    image: '/images/cuts/rindergulasch.jpg',
    visualBrief: 'raw beef stew cubes, dark red marbled meat chunks with bits of fat and sinew, on a board',
  },

  // ── DÜNNUNG & BAUCH ────────────────────────────────────────────────────────
  {
    id: 'flank',
    slug: 'flank',
    species: 'rind',
    primal: 'duennung',
    nameDE: 'Flank Steak',
    nameEN: 'Flank Steak',
    aka: ['Bavette de Flanchet', 'Flanksteak'],
    origin: 'Flanke (unterer Bauch), flacher Muskel',
    blurb: 'Flach, grobfaserig und maximal aromatisch. Heiß und kurz garen, immer gegen die Faser schneiden.',
    facts: '600–900 g · gerne über Nacht marinieren.',
    dna: { marbling: 2, tenderness: 2, fat: 2, flavor: 5, value: 4 },
    doneness: 'Medium Rare (nie darüber)',
    coreTemp: '52–55 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 3, occasions: ['familie', 'gaeste'],
    meatTypeMatch: ['flank'],
    image: '/images/cuts/flank.jpg',
    visualBrief: 'a flat long flank steak with clearly visible long parallel muscle fibers, lean dark red, raw',
    hasGuide: false,
  },
  {
    id: 'bavette',
    slug: 'bavette',
    species: 'rind',
    primal: 'duennung',
    nameDE: 'Bavette',
    nameEN: 'Flap Steak',
    aka: ["Bavette d'Aloyau", 'Sirloin Flap'],
    origin: 'Untere Lende / Dünnung, lockere grobe Faser',
    blurb: 'Lockerer, grobfaseriger Cut mit intensivem Geschmack — saugt Marinaden auf wie ein Schwamm.',
    facts: '500–800 g · gegen die Faser in Tranchen schneiden.',
    dna: { marbling: 3, tenderness: 2, fat: 3, flavor: 5, value: 4 },
    doneness: 'Medium Rare',
    coreTemp: '52–55 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 3, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['bavette', 'flap'],
    image: '/images/cuts/bavette.jpg',
    visualBrief: 'a bavette / flap steak, a loose coarse-grained flat beef muscle with open fibers, raw',
  },
  {
    id: 'skirt',
    slug: 'skirt',
    species: 'rind',
    primal: 'duennung',
    nameDE: 'Skirt Steak',
    nameEN: 'Outside Skirt',
    aka: ['Saumfleisch', 'Zwerchfellpfeiler'],
    origin: 'Zwerchfellbereich, langer schmaler Muskel',
    blurb: 'Der Fajita-Cut: kräftig, grobfaserig, extrem saftig. Sehr heiß, sehr kurz grillen.',
    facts: '400–600 g · der klassische Cut für Tacos & Fajitas.',
    dna: { marbling: 3, tenderness: 2, fat: 3, flavor: 5, value: 4 },
    doneness: 'Medium Rare',
    coreTemp: '52–54 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 3, occasions: ['familie', 'gaeste'],
    meatTypeMatch: ['skirt', 'saumfleisch'],
    image: '/images/cuts/skirt.jpg',
    visualBrief: 'an outside skirt steak, a long thin coarse-grained diaphragm muscle with deep fibers, raw',
  },
  {
    id: 'inside-skirt',
    slug: 'inside-skirt',
    species: 'rind',
    primal: 'duennung',
    nameDE: 'Inside Skirt',
    nameEN: 'Inside Skirt',
    aka: ['Kronfleisch', 'Nierenzapfen-Nachbar'],
    origin: 'Innerer Zwerchfellmuskel',
    blurb: 'Bayerisches Kronfleisch — dünner und etwas magerer als das Outside Skirt, traditionell gekocht oder gegrillt.',
    facts: '300–500 g · in Bayern als Kronfleisch bekannt.',
    dna: { marbling: 2, tenderness: 2, fat: 2, flavor: 5, value: 4 },
    doneness: 'Medium Rare',
    coreTemp: '52–54 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 3, occasions: ['familie'],
    meatTypeMatch: ['inside skirt', 'kronfleisch'],
    image: '/images/cuts/inside-skirt.jpg',
    visualBrief: 'an inside skirt steak, a thin long flat beef muscle with visible grain, raw',
  },
  {
    id: 'denver',
    slug: 'denver',
    species: 'rind',
    primal: 'bug',
    nameDE: 'Denver Cut',
    nameEN: 'Denver Steak',
    aka: ['Unterschulter'],
    origin: 'Aus der Unterschulter (Serratus ventralis), unterhalb des Schulterblatts',
    blurb: 'Stark marmoriert und überraschend zart — der moderne Geheimtipp aus der Schulter, erst durch feineres Zerlegen bekannt geworden.',
    facts: 'Silberhaut entfernen · heiß und kurz grillen · gegen die Faser schneiden.',
    dna: { marbling: 4, tenderness: 3, fat: 3, flavor: 4, value: 4 },
    doneness: 'Medium Rare',
    coreTemp: '54–56 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 3, occasions: ['familie', 'gaeste'],
    meatTypeMatch: ['denver', 'denver cut', 'unterschulter', 'serratus'],
    image: '/images/cuts/denver.jpg',
    visualBrief: 'a denver steak, a well-marbled rectangular beef cut from the chuck under-blade, raw',
    hasGuide: false,
  },
  {
    id: 'onglet',
    slug: 'onglet',
    species: 'rind',
    primal: 'duennung',
    nameDE: 'Onglet',
    nameEN: 'Hanger Steak',
    aka: ['Nierenzapfen', 'Hanging Tender', 'Butcher’s Cut'],
    origin: 'Einzelner Muskel am Zwerchfell, hängt zwischen den Nieren',
    blurb: 'Der intensivste Eigengeschmack aller Cuts — fast mineralisch-leberig. Ein Cut, der polarisiert.',
    facts: 'Nur ein Stück pro Tier · die Mittelsehne entfernen.',
    dna: { marbling: 2, tenderness: 3, fat: 2, flavor: 5, value: 4 },
    doneness: 'Medium Rare (nie darüber)',
    coreTemp: '52–54 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 4, price: 3, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['onglet', 'hanger', 'nierenzapfen'],
    image: '/images/cuts/onglet.jpg',
    visualBrief: 'a single hanger steak (onglet), a thick rope-like muscle with coarse grain and a central sinew, raw',
    hasGuide: false,
  },
  {
    id: 'short-ribs',
    slug: 'short-ribs',
    species: 'rind',
    primal: 'duennung',
    nameDE: 'Short Ribs',
    nameEN: 'Short Ribs',
    aka: ['Querrippe', 'Beef Ribs', 'Tira de Asado'],
    origin: 'Rippenbereich des Bauchs, fleischig am Knochen',
    blurb: 'Fleischige Rippen am Knochen — im Smoker oder Schmortopf zerfallen sie in saftige, kollagenreiche Zartheit.',
    facts: 'Quer (Flanken-Style) oder längs geschnitten.',
    dna: { marbling: 4, tenderness: 2, fat: 4, flavor: 5, value: 3 },
    doneness: 'Low & Slow / Schmoren',
    coreTemp: '90–96 °C',
    methods: ['smoker', 'schmoren', 'grill-indirekt'],
    level: 3, price: 3, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['short rib', 'short ribs', 'beef ribs', 'querrippe', 'tira'],
    image: '/images/cuts/short-ribs.jpg',
    visualBrief: 'thick meaty beef short ribs on the bone, marbled red meat with a fat cap, raw',
  },
  {
    id: 'spider-steak',
    slug: 'spider-steak',
    species: 'rind',
    primal: 'huefte',
    nameDE: 'Spider Steak',
    nameEN: 'Spider Steak',
    aka: ['Kachelfleisch', 'Fledermaus', 'Oyster Steak'],
    origin: 'Kleiner Muskel an der Hüftknochen-Innenseite',
    blurb: 'Ein rarer Metzger-Cut mit netzartiger Fettmaserung (daher der Name) — nur zwei pro Tier.',
    facts: '150–250 g · echte Rarität, beim Metzger erfragen.',
    dna: { marbling: 4, tenderness: 3, fat: 3, flavor: 5, value: 4 },
    doneness: 'Medium Rare',
    coreTemp: '54 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 4, price: 3, occasions: ['date', 'solo'],
    meatTypeMatch: ['spider steak', 'kachelfleisch', 'fledermaus'],
    image: '/images/cuts/spider-steak.jpg',
    visualBrief: 'a spider steak, a small beef cut with a distinctive web-like spider pattern of fat across the surface, raw',
  },

  // ── BRUST ──────────────────────────────────────────────────────────────────
  {
    id: 'brisket',
    slug: 'brisket',
    species: 'rind',
    primal: 'brust',
    nameDE: 'Brisket (Flat)',
    nameEN: 'Brisket Flat',
    aka: ['Brust flach', 'Pastrami-Cut'],
    origin: 'Untere Brust, flacher magerer Teil',
    blurb: 'Der heilige Gral des Texas-BBQ. 12–18 Stunden im Smoker — dann zerfällt das Kollagen vollständig.',
    facts: '3–6 kg ganzes Brisket (Flat + Point).',
    dna: { marbling: 3, tenderness: 2, fat: 4, flavor: 5, value: 3 },
    doneness: 'Low & Slow',
    coreTemp: '90–96 °C',
    methods: ['smoker', 'sous-vide'],
    level: 5, price: 3, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['brisket'],
    image: '/images/cuts/brisket.jpg',
    visualBrief: 'a whole raw beef brisket flat, a large rectangular muscle with a thick white fat cap on one side, raw',
    hasGuide: true,
  },
  {
    id: 'brisket-point',
    slug: 'brisket-point',
    species: 'rind',
    primal: 'brust',
    nameDE: 'Brisket Point',
    nameEN: 'Brisket Point',
    aka: ['Burnt Ends', 'Brust spitz', 'Deckel'],
    origin: 'Obere Brust, fetter durchwachsener Teil',
    blurb: 'Das fettere Point-Stück liefert die legendären Burnt Ends — die wertvollsten Bissen des BBQ.',
    facts: 'Wird zu Würfeln geschnitten, erneut glasiert und geräuchert.',
    dna: { marbling: 5, tenderness: 3, fat: 5, flavor: 5, value: 3 },
    doneness: 'Low & Slow',
    coreTemp: '95–98 °C',
    methods: ['smoker'],
    level: 5, price: 3, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['brisket point', 'burnt ends'],
    image: '/images/cuts/brisket-point.jpg',
    visualBrief: 'a raw beef brisket point, a thick fatty marbled muscle with heavy intramuscular fat, raw',
  },

  // ── BEINSCHEIBE & SONSTIGE ──────────────────────────────────────────────────
  {
    id: 'beinscheibe',
    slug: 'beinscheibe',
    species: 'rind',
    primal: 'beinscheibe_hinten',
    nameDE: 'Beinscheibe',
    nameEN: 'Osso Buco',
    aka: ['Wadschinken', 'Hesse', 'Shank'],
    origin: 'Quer geschnittene Hinter- oder Vorderhesse mit Markknochen',
    blurb: 'Querscheibe mit Markknochen — der Klassiker für Osso Buco. Stundenlanges Schmoren macht sie samtig.',
    facts: '3–4 cm dicke Scheiben · das Mark ist eine Delikatesse.',
    dna: { marbling: 2, tenderness: 1, fat: 3, flavor: 5, value: 5 },
    doneness: 'Schmoren',
    coreTemp: 'weich geschmort',
    methods: ['schmoren'],
    level: 2, price: 2, occasions: ['familie', 'gaeste'],
    meatTypeMatch: ['beinscheibe', 'osso buco', 'wadschinken', 'hesse'],
    image: '/images/cuts/beinscheibe.jpg',
    visualBrief: 'a cross-cut beef shank slice (osso buco) with a round marrow bone in the center surrounded by meat and connective tissue, raw',
  },
  {
    id: 'ochsenschwanz',
    slug: 'ochsenschwanz',
    species: 'rind',
    primal: 'ochsenschwanz',
    nameDE: 'Ochsenschwanz',
    nameEN: 'Oxtail',
    aka: ['Oxtail'],
    origin: 'Schwanz, in Segmente geteilt',
    blurb: 'Kollagenbombe für tiefdunkle Ragouts und Suppen — fällt nach Stunden vom Knochen.',
    facts: 'In Segmente geteilt · ergibt eine gelatinereiche Sauce.',
    dna: { marbling: 3, tenderness: 1, fat: 4, flavor: 5, value: 4 },
    doneness: 'Schmoren',
    coreTemp: 'weich geschmort',
    methods: ['schmoren'],
    level: 2, price: 2, occasions: ['familie', 'gaeste'],
    meatTypeMatch: ['ochsenschwanz', 'oxtail'],
    image: '/images/cuts/ochsenschwanz.jpg',
    visualBrief: 'raw oxtail segments, round cross-cut tail pieces with a bone in the center surrounded by marbled meat, on a board',
  },
  {
    id: 'ochsenbacke',
    slug: 'ochsenbacke',
    species: 'rind',
    primal: 'kopf_backe',
    nameDE: 'Ochsenbacke',
    nameEN: 'Beef Cheek',
    aka: ['Rinderbacke', 'Beef Cheek'],
    origin: 'Kaumuskel der Wange',
    blurb: 'Ein dauerhaft arbeitender Kaumuskel — extrem kollagenreich, geschmort von tiefem Schmelz und Aroma.',
    facts: '300–500 g je Backe · Silberhaut vor dem Schmoren entfernen.',
    dna: { marbling: 2, tenderness: 1, fat: 3, flavor: 5, value: 4 },
    doneness: 'Schmoren / Sous-vide',
    coreTemp: 'weich geschmort / 72 °C (sous-vide)',
    methods: ['schmoren', 'sous-vide'],
    level: 3, price: 2, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['ochsenbacke', 'rinderbacke', 'beef cheek', 'carrillera'],
    image: '/images/cuts/ochsenbacke.jpg',
    visualBrief: 'a raw beef cheek, a round marbled muscle with heavy connective tissue and a silverskin, raw',
  },
  {
    id: 'markknochen',
    slug: 'markknochen',
    species: 'rind',
    primal: 'beinscheibe_vorn',
    nameDE: 'Markknochen',
    nameEN: 'Marrow Bone',
    aka: ['Beinmark', 'Marrow Bone'],
    origin: 'Längs oder quer gesägter Röhrenknochen',
    blurb: 'Geröstetes Knochenmark — nussig, schmelzend, die Umami-Grundlage für Fonds und ein Genuss pur auf Brot.',
    facts: 'Längs (Canoe) oder quer gesägt · 20 min bei 200 °C rösten.',
    dna: { marbling: 5, tenderness: 5, fat: 5, flavor: 4, value: 5 },
    doneness: 'Rösten',
    coreTemp: '200 °C Ofen',
    methods: ['ofen', 'grill-direkt'],
    level: 1, price: 1, occasions: ['gaeste', 'solo'],
    meatTypeMatch: ['markknochen', 'marrow', 'beinmark'],
    image: '/images/cuts/markknochen.jpg',
    visualBrief: 'raw beef marrow bones cut lengthwise exposing the soft white marrow inside the bone, on a board',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SCHWEIN — Teilstücke (Primals)
// ─────────────────────────────────────────────────────────────────────────────

export const PORK_PRIMALS: Primal[] = [
  {
    id: 'kopf',
    species: 'schwein',
    nameDE: 'Kopf',
    nameEN: 'Head',
    blurb: 'Backe und Maske — kollagenreich, ideal geschmort oder für Sülze und Ragout.',
    points: '62,250 86,206 150,196 205,200 205,345 150,352 100,338 80,305',
    labelX: 120, labelY: 272, fontSize: 15, color: '#7c3a10',
  },
  {
    id: 'nacken',
    species: 'schwein',
    nameDE: 'Nacken',
    nameEN: 'Collar',
    blurb: 'Der saftigste Grill-Cut vom Schwein — gut durchwachsen, verzeiht jede Garstufe. Heimat von Presa und Secreto.',
    points: '205,200 330,186 330,288 210,288',
    labelX: 266, labelY: 232, fontSize: 15, color: '#92400e',
  },
  {
    id: 'schulter',
    species: 'schwein',
    nameDE: 'Schulter',
    nameEN: 'Shoulder',
    blurb: 'Der Pulled-Pork-Klassiker — durchwachsen und kollagenreich, perfekt für Low & Slow.',
    points: '210,288 330,288 330,388 270,378 240,360 214,348',
    labelX: 266, labelY: 344, fontSize: 14, color: '#a16207',
  },
  {
    id: 'kotelett',
    species: 'schwein',
    nameDE: 'Kotelett',
    nameEN: 'Loin',
    blurb: 'Der magere Rücken: Kotelett, Karree und das butterzarte Filet. Punktgenau garen, sonst trocken.',
    points: '330,186 560,180 560,288 330,288',
    labelX: 444, labelY: 228, fontSize: 16, color: '#b45309',
  },
  {
    id: 'bauch',
    species: 'schwein',
    nameDE: 'Bauch',
    nameEN: 'Belly',
    blurb: 'Fett, saftig, knusprig — Bauchfleisch, Spareribs und Bacon. Das Herz der Grillkultur.',
    points: '330,288 560,288 560,390 360,392 340,388',
    labelX: 444, labelY: 346, fontSize: 16, color: '#c2610c',
  },
  {
    id: 'schinken',
    species: 'schwein',
    nameDE: 'Schinken',
    nameEN: 'Ham / Leg',
    blurb: 'Die magere Keule — Basis für Schnitzel, Braten und luftgetrocknete Schinken.',
    points: '560,180 600,178 760,200 808,272 784,352 700,378 620,388 560,288',
    labelX: 690, labelY: 282, fontSize: 16, color: '#78350f',
  },
  {
    id: 'haxe',
    species: 'schwein',
    nameDE: 'Haxe / Eisbein',
    nameEN: 'Hock',
    blurb: 'Vordere Haxe (Schweinshaxe) und hintere (Eisbein) — kross gegrillt oder deftig geschmort.',
    points: '694,378 780,372 780,468 694,468',
    labelX: 737, labelY: 534, fontSize: 13, labelColor: '#b89066', color: '#5c2c0a',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SCHWEIN — Cuts
// ─────────────────────────────────────────────────────────────────────────────

export const PORK_CUTS: Cut[] = [
  // ── NACKEN ───────────────────────────────────────────────────────────────
  {
    id: 'schweinenacken',
    slug: 'schweinenacken',
    species: 'schwein',
    primal: 'nacken',
    nameDE: 'Schweinenacken',
    nameEN: 'Pork Collar',
    aka: ['Schopfbraten', 'Kammbraten', 'Nackenbraten'],
    origin: 'Nacken / oberer Hals, gut durchwachsen',
    blurb: 'Der saftigste Braten- und Pulled-Pork-Cut. Das eingelagerte Fett hält ihn auch nach Stunden im Smoker zart.',
    facts: '1,5–2,5 kg am Stück · verzeiht Garfehler wie kein zweiter Cut.',
    dna: { marbling: 4, tenderness: 3, fat: 4, flavor: 4, value: 5 },
    doneness: 'Pulled (Low & Slow) oder saftig medium',
    coreTemp: '90–95 °C (pulled) / 65 °C (Braten)',
    methods: ['smoker', 'grill-indirekt', 'schmoren'],
    level: 2, price: 1, occasions: ['familie', 'gaeste', 'meal-prep'],
    meatTypeMatch: ['schweinenacken', 'schopfbraten', 'kammbraten', 'pork collar'],
    image: '/images/cuts/schweinenacken.jpg',
    visualBrief: 'a whole raw pork collar / neck roast, pale pink marbled meat with seams of white fat, raw',
  },
  {
    id: 'nackensteak',
    slug: 'nackensteak',
    species: 'schwein',
    primal: 'nacken',
    nameDE: 'Nackensteak',
    nameEN: 'Collar Steak',
    aka: ['Schopfsteak', 'Schweinenackensteak'],
    origin: 'Scheibe aus dem Schweinenacken',
    blurb: 'Das beliebteste Grillsteak Deutschlands — günstig, durchwachsen und nahezu narrensicher auf dem Rost.',
    facts: '180–250 g je Steak · der Grillabend-Klassiker.',
    dna: { marbling: 4, tenderness: 3, fat: 4, flavor: 4, value: 5 },
    doneness: 'Durch, aber saftig',
    coreTemp: '65–68 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 1, price: 1, occasions: ['familie', 'solo', 'meal-prep'],
    meatTypeMatch: ['nackensteak', 'schopfsteak'],
    image: '/images/cuts/nackensteak.jpg',
    visualBrief: 'a single raw pork collar steak slice, pale pink with marbling and fat seams, raw',
  },
  {
    id: 'presa',
    slug: 'presa',
    species: 'schwein',
    primal: 'nacken',
    nameDE: 'Presa',
    nameEN: 'Presa Ibérico',
    aka: ['Presa Ibérico', 'Schweinekrone'],
    origin: 'Muskel am Übergang Nacken/Schulter (Ibérico)',
    blurb: 'Der „Filet-Charakter" unter den Ibérico-Cuts: dicht marmoriert, nussig — kurz und rosa gegrillt ein Hochgenuss.',
    facts: '~500 g · nur zwei pro Tier, Ibérico-Spezialität.',
    dna: { marbling: 5, tenderness: 4, fat: 4, flavor: 5, value: 2 },
    doneness: 'Medium (rosa)',
    coreTemp: '63–65 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 4, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['presa'],
    image: '/images/cuts/presa.jpg',
    visualBrief: 'a presa iberico pork cut, a thick richly marbled dark-pink shoulder muscle, raw',
    hasGuide: false,
  },
  {
    id: 'secreto',
    slug: 'secreto',
    species: 'schwein',
    primal: 'nacken',
    nameDE: 'Secreto',
    nameEN: 'Secreto Ibérico',
    aka: ['Secreto Ibérico', 'Geheimnis'],
    origin: 'Dünner Muskel zwischen Schulter und Speck (Ibérico)',
    blurb: 'Das „Geheimnis" des Metzgers — ein dünner, extrem marmorierter Cut, der auf dem Grill zur knusprigen Delikatesse wird.',
    facts: '~200–300 g · wegen der Marmorierung netzartig gemustert.',
    dna: { marbling: 5, tenderness: 4, fat: 5, flavor: 5, value: 2 },
    doneness: 'Medium, knusprig gegrillt',
    coreTemp: '63–65 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 4, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['secreto'],
    image: '/images/cuts/secreto.jpg',
    visualBrief: 'a secreto iberico pork cut, a thin flat sheet of heavily marbled pork with web-like fat pattern, raw',
    hasGuide: false,
  },

  // ── KOTELETT / RÜCKEN ──────────────────────────────────────────────────────
  {
    id: 'kotelett',
    slug: 'kotelett',
    species: 'schwein',
    primal: 'kotelett',
    nameDE: 'Kotelett',
    nameEN: 'Pork Chop',
    aka: ['Schweinekotelett', 'Bone-in Chop'],
    origin: 'Rückenstrang mit Rippenknochen',
    blurb: 'Das klassische Kotelett am Knochen — der Knochen hält es saftig. Mager, daher punktgenau garen.',
    facts: '250–350 g · mit Fettrand für mehr Saftigkeit.',
    dna: { marbling: 2, tenderness: 3, fat: 2, flavor: 4, value: 4 },
    doneness: 'Saftig medium (leicht rosa)',
    coreTemp: '63–65 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 2, price: 2, occasions: ['familie', 'solo'],
    meatTypeMatch: ['kotelett', 'pork chop'],
    image: '/images/cuts/kotelett.jpg',
    visualBrief: 'a single raw bone-in pork chop, pale pink loin meat with a rib bone and a fat rim, raw',
  },
  {
    id: 'karree',
    slug: 'karree',
    species: 'schwein',
    primal: 'kotelett',
    nameDE: 'Karree',
    nameEN: 'Pork Rack',
    aka: ['Schweinekarree', 'Rack of Pork', 'Lummer'],
    origin: 'Ganzer Rückenstrang am Knochen',
    blurb: 'Das ganze Kotelettstück als Braten — beeindruckend als frenched Rack, ideal für Reverse Sear.',
    facts: '1,5–2 kg · als Rack mit freigelegten Knochen ein Hingucker.',
    dna: { marbling: 2, tenderness: 3, fat: 2, flavor: 4, value: 3 },
    doneness: 'Medium (Reverse Sear)',
    coreTemp: '63–65 °C',
    methods: ['grill-indirekt', 'ofen', 'smoker'],
    level: 3, price: 3, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['karree', 'pork rack', 'lummer'],
    image: '/images/cuts/karree.jpg',
    visualBrief: 'a whole raw pork rack roast with frenched rib bones and a fat cap, pale pink loin, raw',
  },
  {
    id: 'schweinefilet',
    slug: 'schweinefilet',
    species: 'schwein',
    primal: 'kotelett',
    nameDE: 'Schweinefilet',
    nameEN: 'Pork Tenderloin',
    aka: ['Lungenbraten', 'Schweinelende', 'Filet Mignon (Pork)'],
    origin: 'Filetstrang unter dem Rücken',
    blurb: 'Der zarteste Cut vom Schwein — sehr mager und schnell gar. Nur kurz garen, dann saftig.',
    facts: '400–600 g · in Minuten übergart, daher aufpassen.',
    dna: { marbling: 1, tenderness: 5, fat: 1, flavor: 3, value: 4 },
    doneness: 'Saftig medium (zart rosa)',
    coreTemp: '63–65 °C',
    methods: ['pfanne', 'grill-direkt', 'sous-vide'],
    level: 2, price: 3, occasions: ['date', 'solo', 'familie'],
    meatTypeMatch: ['schweinefilet', 'lungenbraten', 'schweinelende', 'pork tenderloin'],
    image: '/images/cuts/schweinefilet.jpg',
    visualBrief: 'a whole raw pork tenderloin, a long slender very lean pale-pink muscle, raw',
  },
  {
    id: 'pluma',
    slug: 'pluma',
    species: 'schwein',
    primal: 'kotelett',
    nameDE: 'Pluma',
    nameEN: 'Pluma Ibérico',
    aka: ['Pluma Ibérico', 'Feder'],
    origin: 'Vorderes Ende des Rückens (Ibérico)',
    blurb: 'Federförmiger Ibérico-Cut am Übergang Rücken/Nacken — fein marmoriert, butterzart, kurz gegrillt.',
    facts: '~150–200 g · zarteste Ibérico-Spezialität.',
    dna: { marbling: 5, tenderness: 4, fat: 4, flavor: 5, value: 2 },
    doneness: 'Medium (rosa)',
    coreTemp: '63–65 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 4, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['pluma'],
    image: '/images/cuts/pluma.jpg',
    visualBrief: 'a pluma iberico pork cut, a small feather-shaped well-marbled pink muscle, raw',
    hasGuide: false,
  },
  {
    id: 'kasseler',
    slug: 'kasseler',
    species: 'schwein',
    primal: 'kotelett',
    nameDE: 'Kasseler',
    nameEN: 'Smoked Pork Loin',
    aka: ['Kassler', 'Gepökelter Rücken'],
    origin: 'Gepökelter und geräucherter Rücken/Kotelett',
    blurb: 'Gepökelt und leicht geräuchert — würzig und vorgegart. Nur noch sanft erwärmen, nicht auskochen.',
    facts: 'Rosa Pökelfarbe · klassisch zu Sauerkraut.',
    dna: { marbling: 2, tenderness: 3, fat: 2, flavor: 4, value: 4 },
    doneness: 'Nur erwärmen',
    coreTemp: '60 °C (erwärmen)',
    methods: ['ofen', 'pfanne', 'grill-indirekt'],
    level: 1, price: 2, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['kasseler', 'kassler'],
    image: '/images/cuts/kasseler.jpg',
    visualBrief: 'a raw cured smoked pork loin (kasseler), pink-cured loin meat with a fat edge, raw',
  },

  // ── SCHULTER ───────────────────────────────────────────────────────────────
  {
    id: 'schaeufele',
    slug: 'schaeufele',
    species: 'schwein',
    primal: 'schulter',
    nameDE: 'Schäufele',
    nameEN: 'Pork Shoulder Roast',
    aka: ['Schäufele', 'Schulterbraten am Knochen'],
    origin: 'Schulter mit Schulterblattknochen und Schwarte',
    blurb: 'Der fränkisch-badische Krustenbraten — Schwarte kross, Fleisch saftig. Ein Sonntagsklassiker.',
    facts: '1,5–2 kg · die Schwarte rautenförmig einschneiden.',
    dna: { marbling: 3, tenderness: 2, fat: 4, flavor: 5, value: 5 },
    doneness: 'Durchgegart, Schwarte kross',
    coreTemp: '80–85 °C',
    methods: ['ofen', 'grill-indirekt'],
    level: 3, price: 1, occasions: ['familie', 'gaeste'],
    meatTypeMatch: ['schäufele', 'schaeufele', 'krustenbraten'],
    image: '/images/cuts/schaeufele.jpg',
    visualBrief: 'a raw pork shoulder roast with the rind / skin on, scored crackling skin and pink meat, raw',
  },
  {
    id: 'schulterbraten',
    slug: 'schulterbraten',
    species: 'schwein',
    primal: 'schulter',
    nameDE: 'Schweineschulter',
    nameEN: 'Pork Shoulder',
    aka: ['Schulterbraten', 'Bug', 'Boston Butt'],
    origin: 'Schulter / Bug, ohne Knochen',
    blurb: 'Der Pulled-Pork-Cut schlechthin — viel Bindegewebe, das beim langen Räuchern zu saftiger Zartheit zerfällt.',
    facts: '2–4 kg · Boston Butt ist der obere Teil der Schulter.',
    dna: { marbling: 4, tenderness: 2, fat: 4, flavor: 5, value: 5 },
    doneness: 'Pulled (Low & Slow)',
    coreTemp: '92–96 °C',
    methods: ['smoker', 'schmoren', 'grill-indirekt'],
    level: 3, price: 1, occasions: ['gaeste', 'familie', 'meal-prep'],
    meatTypeMatch: ['schweineschulter', 'schulterbraten', 'pulled pork', 'boston butt', 'pork shoulder'],
    image: '/images/cuts/schulterbraten.jpg',
    visualBrief: 'a whole raw boneless pork shoulder (boston butt), a thick marbled pink roast with fat seams, raw',
    hasGuide: false,
  },
  {
    id: 'schweinegulasch',
    slug: 'schweinegulasch',
    species: 'schwein',
    primal: 'schulter',
    nameDE: 'Schweinegulasch',
    nameEN: 'Pork Stew Meat',
    aka: ['Gulasch', 'Würfelfleisch'],
    origin: 'Würfel aus Schulter oder Bauch',
    blurb: 'Gewürfeltes Schmorfleisch aus der Schulter — günstig und dankbar für Gulasch, Curry und Eintöpfe.',
    facts: '3 cm Würfel · scharf anbraten, dann schmoren.',
    dna: { marbling: 3, tenderness: 2, fat: 3, flavor: 4, value: 5 },
    doneness: 'Schmoren',
    coreTemp: 'weich geschmort',
    methods: ['schmoren'],
    level: 1, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['schweinegulasch', 'pork stew'],
    image: '/images/cuts/schweinegulasch.jpg',
    visualBrief: 'raw pork stew cubes, pale pink meat chunks with bits of fat, on a board',
  },

  // ── BAUCH ────────────────────────────────────────────────────────────────
  {
    id: 'schweinebauch',
    slug: 'schweinebauch',
    species: 'schwein',
    primal: 'bauch',
    nameDE: 'Schweinebauch',
    nameEN: 'Pork Belly',
    aka: ['Bauchfleisch', 'Wammerl', 'Pork Belly'],
    origin: 'Bauch mit Schwarte, Schichten aus Fett und Fleisch',
    blurb: 'Knusprige Kruste, schmelzendes Fett, saftiges Fleisch — vom Krustenbraten bis Bao Buns ein Allrounder.',
    facts: 'Schichtaufbau Fleisch/Fett · Schwarte für Crackling einschneiden.',
    dna: { marbling: 5, tenderness: 3, fat: 5, flavor: 5, value: 4 },
    doneness: 'Durch, Schwarte kross',
    coreTemp: '75–85 °C',
    methods: ['ofen', 'grill-indirekt', 'smoker'],
    level: 3, price: 2, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['schweinebauch', 'bauchfleisch', 'pork belly', 'wammerl'],
    image: '/images/cuts/schweinebauch.jpg',
    visualBrief: 'a raw pork belly slab with scored skin, alternating layers of pink meat and white fat, raw',
  },
  {
    id: 'spareribs',
    slug: 'spareribs',
    species: 'schwein',
    primal: 'bauch',
    nameDE: 'Spareribs',
    nameEN: 'Spare Ribs',
    aka: ['St. Louis Cut', 'Rippchen'],
    origin: 'Rippen aus dem Bauch',
    blurb: 'Die BBQ-Ikone — im Smoker bei 110 °C, bis das Fleisch fast vom Knochen fällt. 3-2-1 für Einsteiger.',
    facts: 'St. Louis = sauber zugeschnitten · Silberhaut abziehen.',
    dna: { marbling: 4, tenderness: 3, fat: 4, flavor: 5, value: 4 },
    doneness: 'Low & Slow',
    coreTemp: '90–94 °C',
    methods: ['smoker', 'grill-indirekt'],
    level: 3, price: 2, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['spareribs', 'spare ribs', 'rippchen', 'st. louis'],
    image: '/images/cuts/spareribs.jpg',
    visualBrief: 'a raw rack of pork spare ribs, pink meat over a row of curved rib bones, raw',
    hasGuide: false,
  },
  {
    id: 'baby-back-ribs',
    slug: 'baby-back-ribs',
    species: 'schwein',
    primal: 'bauch',
    nameDE: 'Baby Back Ribs',
    nameEN: 'Baby Back Ribs',
    aka: ['Loin Ribs', 'Kotelettrippchen', 'Schälrippchen'],
    origin: 'Kürzere Rippen am Übergang zum Rücken',
    blurb: 'Kürzer, zarter und magerer als Spareribs — schneller gar und besonders fleischig.',
    facts: 'Kürzere, gebogene Knochen · zarter als Spareribs.',
    dna: { marbling: 3, tenderness: 3, fat: 3, flavor: 4, value: 3 },
    doneness: 'Low & Slow',
    coreTemp: '90–93 °C',
    methods: ['smoker', 'grill-indirekt'],
    level: 3, price: 3, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['baby back', 'loin ribs', 'kotelettrippchen', 'schälrippchen'],
    image: '/images/cuts/baby-back-ribs.jpg',
    visualBrief: 'a raw rack of baby back pork ribs, short curved bones with pink meat, raw',
  },
  {
    id: 'bauchspeck',
    slug: 'bauchspeck',
    species: 'schwein',
    primal: 'bauch',
    nameDE: 'Bauchspeck',
    nameEN: 'Bacon',
    aka: ['Bacon', 'Frühstücksspeck', 'Pancetta'],
    origin: 'Gepökelter / geräucherter Schweinebauch',
    blurb: 'Gepökelter und geräucherter Bauch — knusprig gebraten der Umami-Booster für alles.',
    facts: 'In Scheiben oder am Stück · Pancetta = ungeräuchert.',
    dna: { marbling: 5, tenderness: 3, fat: 5, flavor: 5, value: 4 },
    doneness: 'Knusprig braten',
    coreTemp: 'kross gebraten',
    methods: ['pfanne', 'ofen'],
    level: 1, price: 2, occasions: ['solo', 'familie'],
    meatTypeMatch: ['bauchspeck', 'bacon', 'pancetta', 'speck'],
    image: '/images/cuts/bauchspeck.jpg',
    visualBrief: 'raw streaky bacon slices, pink meat striped with white fat, on a board',
  },
  {
    id: 'abanico',
    slug: 'abanico',
    species: 'schwein',
    primal: 'bauch',
    nameDE: 'Abanico',
    nameEN: 'Abanico Ibérico',
    aka: ['Abanico Ibérico', 'Fächer'],
    origin: 'Muskel über den Rippen (Ibérico)',
    blurb: 'Fächerförmiger Ibérico-Cut über den Rippen — dünn, marmoriert, ideal für die heiße Plancha.',
    facts: '~200 g · Name bedeutet „Fächer".',
    dna: { marbling: 5, tenderness: 3, fat: 4, flavor: 5, value: 2 },
    doneness: 'Medium, knusprig',
    coreTemp: '63–65 °C',
    methods: ['grill-direkt', 'pfanne'],
    level: 3, price: 4, occasions: ['date', 'gaeste'],
    meatTypeMatch: ['abanico'],
    image: '/images/cuts/abanico.jpg',
    visualBrief: 'an abanico iberico pork cut, a thin fan-shaped marbled pink muscle from over the ribs, raw',
  },

  // ── SCHINKEN / KEULE ────────────────────────────────────────────────────────
  {
    id: 'schinkenbraten',
    slug: 'schinkenbraten',
    species: 'schwein',
    primal: 'schinken',
    nameDE: 'Schinkenbraten',
    nameEN: 'Fresh Ham',
    aka: ['Keule', 'Hinterschinken', 'Schlegel'],
    origin: 'Ganze Hinterkeule, mager',
    blurb: 'Die magere Keule als Braten — mit Schwarte ein Krustenbraten, ohne ein schlanker Sonntagsbraten.',
    facts: 'Bis 5 kg · auch Rohstoff für luftgetrockneten Schinken.',
    dna: { marbling: 2, tenderness: 2, fat: 2, flavor: 4, value: 5 },
    doneness: 'Durchgegart, saftig',
    coreTemp: '70–75 °C',
    methods: ['ofen', 'grill-indirekt'],
    level: 3, price: 1, occasions: ['familie', 'gaeste'],
    meatTypeMatch: ['schinkenbraten', 'keule', 'hinterschinken', 'fresh ham'],
    image: '/images/cuts/schinkenbraten.jpg',
    visualBrief: 'a whole raw fresh ham (pork leg) roast with rind, lean pale-pink meat, raw',
  },
  {
    id: 'oberschale-schwein',
    slug: 'oberschale-schwein',
    species: 'schwein',
    primal: 'schinken',
    nameDE: 'Oberschale',
    nameEN: 'Topside',
    aka: ['Schnitzelfleisch', 'Nuss'],
    origin: 'Innenseite der Keule, großer magerer Muskel',
    blurb: 'Der magerste Teil der Keule — das klassische Schnitzelfleisch, kurz und heiß gebraten.',
    facts: 'Dünn plattiert für Schnitzel · sehr mager.',
    dna: { marbling: 1, tenderness: 3, fat: 1, flavor: 3, value: 5 },
    doneness: 'Kurz & heiß (Schnitzel)',
    coreTemp: 'kurz gebraten',
    methods: ['pfanne'],
    level: 1, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['oberschale', 'schnitzelfleisch'],
    image: '/images/cuts/oberschale-schwein.jpg',
    visualBrief: 'a large lean raw pork topside roast, a uniform pale-pink muscle with little fat, raw',
  },
  {
    id: 'schweineschnitzel',
    slug: 'schweineschnitzel',
    species: 'schwein',
    primal: 'schinken',
    nameDE: 'Schnitzel',
    nameEN: 'Schnitzel',
    aka: ['Schweineschnitzel', 'Wiener Art'],
    origin: 'Dünn geschnittene Scheibe aus der Oberschale',
    blurb: 'Dünn plattiert, paniert und goldbraun ausgebacken — die deutsche Wirtshaus-Institution.',
    facts: '120–180 g · auf 0,5 cm plattieren.',
    dna: { marbling: 1, tenderness: 3, fat: 1, flavor: 3, value: 5 },
    doneness: 'Kurz & heiß',
    coreTemp: 'goldbraun gebacken',
    methods: ['pfanne'],
    level: 1, price: 1, occasions: ['familie', 'solo'],
    meatTypeMatch: ['schnitzel'],
    image: '/images/cuts/schweineschnitzel.jpg',
    visualBrief: 'a raw thin flattened pork schnitzel cutlet, a pale-pink lean slice, raw',
  },
  {
    id: 'nuss-schwein',
    slug: 'nuss-schwein',
    species: 'schwein',
    primal: 'schinken',
    nameDE: 'Nuss',
    nameEN: 'Knuckle',
    aka: ['Kugel', 'Maus'],
    origin: 'Runder Muskel der Keule',
    blurb: 'Magerer, feinfaseriger Keulenmuskel — ideal als kleiner Braten oder für Geschnetzeltes.',
    facts: '1–1,5 kg · zart, wenn nicht übergart.',
    dna: { marbling: 1, tenderness: 3, fat: 1, flavor: 3, value: 5 },
    doneness: 'Saftig medium / Braten',
    coreTemp: '63–68 °C',
    methods: ['ofen', 'pfanne', 'sous-vide'],
    level: 2, price: 1, occasions: ['familie', 'meal-prep'],
    meatTypeMatch: ['nuss', 'kugel'],
    image: '/images/cuts/nuss-schwein.jpg',
    visualBrief: 'a round lean raw pork knuckle muscle, a smooth pale-pink ball-shaped cut, raw',
  },

  // ── HAXE / EISBEIN ──────────────────────────────────────────────────────────
  {
    id: 'haxe',
    slug: 'haxe',
    species: 'schwein',
    primal: 'haxe',
    nameDE: 'Schweinshaxe',
    nameEN: 'Pork Knuckle',
    aka: ['Haxe', 'Stelze', 'Schweinshaxn'],
    origin: 'Vordere oder hintere Unterschenkel mit Schwarte',
    blurb: 'Bayerische Wirtshaus-Ikone: außen rösch-knusprige Kruste, innen butterweiches Fleisch.',
    facts: '0,8–1,2 kg je Haxe · erst kochen/dämpfen, dann krossen.',
    dna: { marbling: 3, tenderness: 2, fat: 4, flavor: 5, value: 5 },
    doneness: 'Weich, Kruste kross',
    coreTemp: '85–90 °C',
    methods: ['ofen', 'grill-indirekt', 'schmoren'],
    level: 3, price: 1, occasions: ['gaeste', 'familie'],
    meatTypeMatch: ['haxe', 'stelze', 'pork knuckle'],
    image: '/images/cuts/haxe.jpg',
    visualBrief: 'a whole raw pork knuckle (hock) with scored skin on the bone, pink meat, raw',
  },
  {
    id: 'eisbein',
    slug: 'eisbein',
    species: 'schwein',
    primal: 'haxe',
    nameDE: 'Eisbein',
    nameEN: 'Cured Ham Hock',
    aka: ['Hintere Haxe', 'Gepökelte Haxe'],
    origin: 'Gepökelte hintere Haxe',
    blurb: 'Die norddeutsche, gepökelte und gekochte Haxe — zart-glasig, klassisch zu Erbspüree und Sauerkraut.',
    facts: 'Gepökelt → rosa · wird gekocht, nicht knusprig.',
    dna: { marbling: 3, tenderness: 2, fat: 4, flavor: 4, value: 5 },
    doneness: 'Weich gekocht',
    coreTemp: '85 °C (gekocht)',
    methods: ['schmoren'],
    level: 2, price: 1, occasions: ['familie'],
    meatTypeMatch: ['eisbein'],
    image: '/images/cuts/eisbein.jpg',
    visualBrief: 'a raw cured pork hock (eisbein), pink-cured meat on the bone with skin, raw',
  },

  // ── KOPF ───────────────────────────────────────────────────────────────────
  {
    id: 'schweinebacke',
    slug: 'schweinebacke',
    species: 'schwein',
    primal: 'kopf',
    nameDE: 'Schweinebäckchen',
    nameEN: 'Pork Cheek',
    aka: ['Carrillera', 'Backe', 'Pork Cheek'],
    origin: 'Kaumuskel der Wange',
    blurb: 'Ständig arbeitender Kaumuskel — geschmort zergeht er auf der Zunge, ein unterschätztes Schmuckstück.',
    facts: '60–90 g je Bäckchen · Silberhaut entfernen.',
    dna: { marbling: 3, tenderness: 1, fat: 3, flavor: 5, value: 4 },
    doneness: 'Schmoren / Sous-vide',
    coreTemp: 'weich geschmort / 72 °C (sous-vide)',
    methods: ['schmoren', 'sous-vide'],
    level: 3, price: 2, occasions: ['gaeste', 'date'],
    meatTypeMatch: ['schweinebacke', 'bäckchen', 'carrillera', 'pork cheek'],
    image: '/images/cuts/schweinebacke.jpg',
    visualBrief: 'raw pork cheeks, small round marbled pink muscles with connective tissue, on a board',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

export const ALL_CUTS: Cut[] = [...BEEF_CUTS, ...PORK_CUTS];
export const ALL_PRIMALS: Primal[] = [...BEEF_PRIMALS, ...PORK_PRIMALS];

export function getCutsBySpecies(species: Species): Cut[] {
  return ALL_CUTS.filter((c) => c.species === species);
}

export function getPrimalsBySpecies(species: Species): Primal[] {
  return ALL_PRIMALS.filter((p) => p.species === species);
}

export function getCutById(id: string): Cut | undefined {
  return ALL_CUTS.find((c) => c.id === id);
}

export function getCutsByPrimal(primalId: string): Cut[] {
  return ALL_CUTS.filter((c) => c.primal === primalId);
}

export const DNA_AXES: { key: keyof CutDna; label: string }[] = [
  { key: 'marbling', label: 'Marmorierung' },
  { key: 'tenderness', label: 'Zartheit' },
  { key: 'fat', label: 'Fett' },
  { key: 'flavor', label: 'Aroma' },
  { key: 'value', label: 'Preis-Leistung' },
];
